/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionRouteImport } from './routes/$section'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as CustomersIdRouteImport } from './routes/customers_.$id'
import { Route as InventoryIdRouteImport } from './routes/inventory_.$id'
import { Route as OrdersIdRouteImport } from './routes/orders_.$id'
import { Route as ProductsIdRouteImport } from './routes/products_.$id'
import { Route as ProductsNewRouteImport } from './routes/products_.new'
import { Route as PromotionsIdRouteImport } from './routes/promotions_.$id'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as StoreCurrenciesRouteImport } from './routes/store.currencies'
import { Route as StoreKeysRouteImport } from './routes/store.keys'
import { Route as StoreRegionsRouteImport } from './routes/store.regions'
import { Route as StoreSalesChannelsRouteImport } from './routes/store.sales-channels'
import { Route as SubscriptionsIdRouteImport } from './routes/subscriptions_.$id'
import { Route as StoreCurrenciesNewRouteImport } from './routes/store_.currencies.new'
import { Route as StoreKeysNewRouteImport } from './routes/store_.keys.new'
import { Route as StoreRegionsIdRouteImport } from './routes/store_.regions.$id'
import { Route as StoreRegionsNewRouteImport } from './routes/store_.regions.new'
import { Route as StoreSalesChannelsIdRouteImport } from './routes/store_.sales-channels.$id'
import { Route as StoreSalesChannelsNewRouteImport } from './routes/store_.sales-channels.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionRoute = SectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers_/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIdRoute = InventoryIdRouteImport.update({
  id: '/inventory_/$id',
  path: '/inventory/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders_/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products_/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products_/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsIdRoute = PromotionsIdRouteImport.update({
  id: '/promotions_/$id',
  path: '/promotions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCurrenciesRoute = StoreCurrenciesRouteImport.update({
  id: '/currencies',
  path: '/currencies',
  getParentRoute: () => StoreRoute,
} as any)
const StoreKeysRoute = StoreKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => StoreRoute,
} as any)
const StoreRegionsRoute = StoreRegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => StoreRoute,
} as any)
const StoreSalesChannelsRoute = StoreSalesChannelsRouteImport.update({
  id: '/sales-channels',
  path: '/sales-channels',
  getParentRoute: () => StoreRoute,
} as any)
const SubscriptionsIdRoute = SubscriptionsIdRouteImport.update({
  id: '/subscriptions_/$id',
  path: '/subscriptions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreCurrenciesNewRoute = StoreCurrenciesNewRouteImport.update({
  id: '/store_/currencies/new',
  path: '/store/currencies/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreKeysNewRoute = StoreKeysNewRouteImport.update({
  id: '/store_/keys/new',
  path: '/store/keys/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRegionsIdRoute = StoreRegionsIdRouteImport.update({
  id: '/store_/regions/$id',
  path: '/store/regions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRegionsNewRoute = StoreRegionsNewRouteImport.update({
  id: '/store_/regions/new',
  path: '/store/regions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSalesChannelsIdRoute = StoreSalesChannelsIdRouteImport.update({
  id: '/store_/sales-channels/$id',
  path: '/store/sales-channels/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSalesChannelsNewRoute = StoreSalesChannelsNewRouteImport.update({
  id: '/store_/sales-channels/new',
  path: '/store/sales-channels/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/promotions': typeof PromotionsRoute
  '/store': typeof StoreRouteWithChildren
  '/subscriptions': typeof SubscriptionsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/new': typeof ProductsNewRoute
  '/promotions/$id': typeof PromotionsIdRoute
  '/store/currencies': typeof StoreCurrenciesRoute
  '/store/keys': typeof StoreKeysRoute
  '/store/regions': typeof StoreRegionsRoute
  '/store/sales-channels': typeof StoreSalesChannelsRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/store/': typeof StoreIndexRoute
  '/store/currencies/new': typeof StoreCurrenciesNewRoute
  '/store/keys/new': typeof StoreKeysNewRoute
  '/store/regions/$id': typeof StoreRegionsIdRoute
  '/store/regions/new': typeof StoreRegionsNewRoute
  '/store/sales-channels/$id': typeof StoreSalesChannelsIdRoute
  '/store/sales-channels/new': typeof StoreSalesChannelsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/promotions': typeof PromotionsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/new': typeof ProductsNewRoute
  '/promotions/$id': typeof PromotionsIdRoute
  '/store/currencies': typeof StoreCurrenciesRoute
  '/store/keys': typeof StoreKeysRoute
  '/store/regions': typeof StoreRegionsRoute
  '/store/sales-channels': typeof StoreSalesChannelsRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/store': typeof StoreIndexRoute
  '/store/currencies/new': typeof StoreCurrenciesNewRoute
  '/store/keys/new': typeof StoreKeysNewRoute
  '/store/regions/$id': typeof StoreRegionsIdRoute
  '/store/regions/new': typeof StoreRegionsNewRoute
  '/store/sales-channels/$id': typeof StoreSalesChannelsIdRoute
  '/store/sales-channels/new': typeof StoreSalesChannelsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/promotions': typeof PromotionsRoute
  '/store': typeof StoreRouteWithChildren
  '/subscriptions': typeof SubscriptionsRoute
  '/customers_/$id': typeof CustomersIdRoute
  '/inventory_/$id': typeof InventoryIdRoute
  '/orders_/$id': typeof OrdersIdRoute
  '/products_/$id': typeof ProductsIdRoute
  '/products_/new': typeof ProductsNewRoute
  '/promotions_/$id': typeof PromotionsIdRoute
  '/store/currencies': typeof StoreCurrenciesRoute
  '/store/keys': typeof StoreKeysRoute
  '/store/regions': typeof StoreRegionsRoute
  '/store/sales-channels': typeof StoreSalesChannelsRoute
  '/subscriptions_/$id': typeof SubscriptionsIdRoute
  '/store/': typeof StoreIndexRoute
  '/store_/currencies/new': typeof StoreCurrenciesNewRoute
  '/store_/keys/new': typeof StoreKeysNewRoute
  '/store_/regions/$id': typeof StoreRegionsIdRoute
  '/store_/regions/new': typeof StoreRegionsNewRoute
  '/store_/sales-channels/$id': typeof StoreSalesChannelsIdRoute
  '/store_/sales-channels/new': typeof StoreSalesChannelsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$section'
    | '/customers'
    | '/inventory'
    | '/orders'
    | '/products'
    | '/promotions'
    | '/store'
    | '/subscriptions'
    | '/customers/$id'
    | '/inventory/$id'
    | '/orders/$id'
    | '/products/$id'
    | '/products/new'
    | '/promotions/$id'
    | '/store/currencies'
    | '/store/keys'
    | '/store/regions'
    | '/store/sales-channels'
    | '/subscriptions/$id'
    | '/store/'
    | '/store/currencies/new'
    | '/store/keys/new'
    | '/store/regions/$id'
    | '/store/regions/new'
    | '/store/sales-channels/$id'
    | '/store/sales-channels/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$section'
    | '/customers'
    | '/inventory'
    | '/orders'
    | '/products'
    | '/promotions'
    | '/subscriptions'
    | '/customers/$id'
    | '/inventory/$id'
    | '/orders/$id'
    | '/products/$id'
    | '/products/new'
    | '/promotions/$id'
    | '/store/currencies'
    | '/store/keys'
    | '/store/regions'
    | '/store/sales-channels'
    | '/subscriptions/$id'
    | '/store'
    | '/store/currencies/new'
    | '/store/keys/new'
    | '/store/regions/$id'
    | '/store/regions/new'
    | '/store/sales-channels/$id'
    | '/store/sales-channels/new'
  id:
    | '__root__'
    | '/'
    | '/$section'
    | '/customers'
    | '/inventory'
    | '/orders'
    | '/products'
    | '/promotions'
    | '/store'
    | '/subscriptions'
    | '/customers_/$id'
    | '/inventory_/$id'
    | '/orders_/$id'
    | '/products_/$id'
    | '/products_/new'
    | '/promotions_/$id'
    | '/store/currencies'
    | '/store/keys'
    | '/store/regions'
    | '/store/sales-channels'
    | '/subscriptions_/$id'
    | '/store/'
    | '/store_/currencies/new'
    | '/store_/keys/new'
    | '/store_/regions/$id'
    | '/store_/regions/new'
    | '/store_/sales-channels/$id'
    | '/store_/sales-channels/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectionRoute: typeof SectionRoute
  CustomersRoute: typeof CustomersRoute
  InventoryRoute: typeof InventoryRoute
  OrdersRoute: typeof OrdersRoute
  ProductsRoute: typeof ProductsRoute
  PromotionsRoute: typeof PromotionsRoute
  StoreRoute: typeof StoreRouteWithChildren
  SubscriptionsRoute: typeof SubscriptionsRoute
  CustomersIdRoute: typeof CustomersIdRoute
  InventoryIdRoute: typeof InventoryIdRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsNewRoute: typeof ProductsNewRoute
  PromotionsIdRoute: typeof PromotionsIdRoute
  SubscriptionsIdRoute: typeof SubscriptionsIdRoute
  StoreCurrenciesNewRoute: typeof StoreCurrenciesNewRoute
  StoreKeysNewRoute: typeof StoreKeysNewRoute
  StoreRegionsIdRoute: typeof StoreRegionsIdRoute
  StoreRegionsNewRoute: typeof StoreRegionsNewRoute
  StoreSalesChannelsIdRoute: typeof StoreSalesChannelsIdRoute
  StoreSalesChannelsNewRoute: typeof StoreSalesChannelsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section': {
      id: '/$section'
      path: '/$section'
      fullPath: '/$section'
      preLoaderRoute: typeof SectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers_/$id': {
      id: '/customers_/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory_/$id': {
      id: '/inventory_/$id'
      path: '/inventory/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof InventoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders_/$id': {
      id: '/orders_/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$id': {
      id: '/products_/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/new': {
      id: '/products_/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions_/$id': {
      id: '/promotions_/$id'
      path: '/promotions/$id'
      fullPath: '/promotions/$id'
      preLoaderRoute: typeof PromotionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/currencies': {
      id: '/store/currencies'
      path: '/currencies'
      fullPath: '/store/currencies'
      preLoaderRoute: typeof StoreCurrenciesRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/keys': {
      id: '/store/keys'
      path: '/keys'
      fullPath: '/store/keys'
      preLoaderRoute: typeof StoreKeysRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/regions': {
      id: '/store/regions'
      path: '/regions'
      fullPath: '/store/regions'
      preLoaderRoute: typeof StoreRegionsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/sales-channels': {
      id: '/store/sales-channels'
      path: '/sales-channels'
      fullPath: '/store/sales-channels'
      preLoaderRoute: typeof StoreSalesChannelsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/subscriptions_/$id': {
      id: '/subscriptions_/$id'
      path: '/subscriptions/$id'
      fullPath: '/subscriptions/$id'
      preLoaderRoute: typeof SubscriptionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store_/currencies/new': {
      id: '/store_/currencies/new'
      path: '/store/currencies/new'
      fullPath: '/store/currencies/new'
      preLoaderRoute: typeof StoreCurrenciesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store_/keys/new': {
      id: '/store_/keys/new'
      path: '/store/keys/new'
      fullPath: '/store/keys/new'
      preLoaderRoute: typeof StoreKeysNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store_/regions/$id': {
      id: '/store_/regions/$id'
      path: '/store/regions/$id'
      fullPath: '/store/regions/$id'
      preLoaderRoute: typeof StoreRegionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store_/regions/new': {
      id: '/store_/regions/new'
      path: '/store/regions/new'
      fullPath: '/store/regions/new'
      preLoaderRoute: typeof StoreRegionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store_/sales-channels/$id': {
      id: '/store_/sales-channels/$id'
      path: '/store/sales-channels/$id'
      fullPath: '/store/sales-channels/$id'
      preLoaderRoute: typeof StoreSalesChannelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store_/sales-channels/new': {
      id: '/store_/sales-channels/new'
      path: '/store/sales-channels/new'
      fullPath: '/store/sales-channels/new'
      preLoaderRoute: typeof StoreSalesChannelsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StoreRouteChildren {
  StoreCurrenciesRoute: typeof StoreCurrenciesRoute
  StoreKeysRoute: typeof StoreKeysRoute
  StoreRegionsRoute: typeof StoreRegionsRoute
  StoreSalesChannelsRoute: typeof StoreSalesChannelsRoute
  StoreIndexRoute: typeof StoreIndexRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreCurrenciesRoute: StoreCurrenciesRoute,
  StoreKeysRoute: StoreKeysRoute,
  StoreRegionsRoute: StoreRegionsRoute,
  StoreSalesChannelsRoute: StoreSalesChannelsRoute,
  StoreIndexRoute: StoreIndexRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectionRoute: SectionRoute,
  CustomersRoute: CustomersRoute,
  InventoryRoute: InventoryRoute,
  OrdersRoute: OrdersRoute,
  ProductsRoute: ProductsRoute,
  PromotionsRoute: PromotionsRoute,
  StoreRoute: StoreRouteWithChildren,
  SubscriptionsRoute: SubscriptionsRoute,
  CustomersIdRoute: CustomersIdRoute,
  InventoryIdRoute: InventoryIdRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  ProductsNewRoute: ProductsNewRoute,
  PromotionsIdRoute: PromotionsIdRoute,
  SubscriptionsIdRoute: SubscriptionsIdRoute,
  StoreCurrenciesNewRoute: StoreCurrenciesNewRoute,
  StoreKeysNewRoute: StoreKeysNewRoute,
  StoreRegionsIdRoute: StoreRegionsIdRoute,
  StoreRegionsNewRoute: StoreRegionsNewRoute,
  StoreSalesChannelsIdRoute: StoreSalesChannelsIdRoute,
  StoreSalesChannelsNewRoute: StoreSalesChannelsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
