/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionRouteImport } from './routes/$section'
import { Route as BasketsRouteImport } from './routes/baskets'
import { Route as CartsRouteImport } from './routes/carts'
import { Route as CreditRouteImport } from './routes/credit'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as FulfilmentRouteImport } from './routes/fulfilment'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as BasketsIdRouteImport } from './routes/baskets_.$id'
import { Route as CreditIdRouteImport } from './routes/credit_.$id'
import { Route as CustomersIdRouteImport } from './routes/customers_.$id'
import { Route as FulfilmentIndexRouteImport } from './routes/fulfilment.index'
import { Route as FulfilmentProvidersRouteImport } from './routes/fulfilment.providers'
import { Route as FulfilmentSetsRouteImport } from './routes/fulfilment.sets'
import { Route as FulfilmentShippingOptionTypesRouteImport } from './routes/fulfilment.shipping-option-types'
import { Route as FulfilmentShippingOptionsRouteImport } from './routes/fulfilment.shipping-options'
import { Route as FulfilmentShippingProfilesRouteImport } from './routes/fulfilment.shipping-profiles'
import { Route as InventoryIdRouteImport } from './routes/inventory_.$id'
import { Route as OrdersIdRouteImport } from './routes/orders_.$id'
import { Route as PaymentsIndexRouteImport } from './routes/payments.index'
import { Route as PaymentsRefundReasonsRouteImport } from './routes/payments.refund-reasons'
import { Route as PaymentsIdRouteImport } from './routes/payments_.$id'
import { Route as PayoutsIndexRouteImport } from './routes/payouts.index'
import { Route as PayoutsCommissionRulesRouteImport } from './routes/payouts.commission-rules'
import { Route as PricingIndexRouteImport } from './routes/pricing.index'
import { Route as PricingPriceListsRouteImport } from './routes/pricing.price-lists'
import { Route as PricingPricePreferencesRouteImport } from './routes/pricing.price-preferences'
import { Route as PricingPriceSetsRouteImport } from './routes/pricing.price-sets'
import { Route as PricingPricesRouteImport } from './routes/pricing.prices'
import { Route as ProductsNewRouteImport } from './routes/products.new'
import { Route as ProductsIdRouteImport } from './routes/products_.$id'
import { Route as PromotionsIdRouteImport } from './routes/promotions_.$id'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as StoreCurrenciesRouteImport } from './routes/store.currencies'
import { Route as StoreKeysRouteImport } from './routes/store.keys'
import { Route as StoreRegionsRouteImport } from './routes/store.regions'
import { Route as StoreSalesChannelsRouteImport } from './routes/store.sales-channels'
import { Route as SubscriptionsIdRouteImport } from './routes/subscriptions_.$id'
import { Route as TaxIndexRouteImport } from './routes/tax.index'
import { Route as TaxRatesRouteImport } from './routes/tax.rates'
import { Route as TaxRegionsRouteImport } from './routes/tax.regions'
import { Route as TaxRegistrationsRouteImport } from './routes/tax.registrations'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows.index'
import { Route as WorkflowsDeadLettersRouteImport } from './routes/workflows.dead-letters'
import { Route as WorkflowsIdRouteImport } from './routes/workflows_.$id'
import { Route as CustomersIdEditRouteImport } from './routes/customers_.$id.edit'
import { Route as FulfilmentShippingOptionsIdRouteImport } from './routes/fulfilment_.shipping-options.$id'
import { Route as FulfilmentShippingProfilesIdRouteImport } from './routes/fulfilment_.shipping-profiles.$id'
import { Route as PricingPriceListsIdRouteImport } from './routes/pricing_.price-lists.$id'
import { Route as ProductsIdEditRouteImport } from './routes/products_.$id.edit'
import { Route as PromotionsIdEditRouteImport } from './routes/promotions_.$id.edit'
import { Route as StoreCurrenciesNewRouteImport } from './routes/store.currencies.new'
import { Route as StoreKeysNewRouteImport } from './routes/store.keys.new'
import { Route as StoreRegionsNewRouteImport } from './routes/store.regions.new'
import { Route as StoreSalesChannelsNewRouteImport } from './routes/store.sales-channels.new'
import { Route as StoreRegionsIdRouteImport } from './routes/store_.regions.$id'
import { Route as StoreSalesChannelsIdRouteImport } from './routes/store_.sales-channels.$id'
import { Route as TaxRatesIdRouteImport } from './routes/tax_.rates.$id'
import { Route as TaxRegionsIdRouteImport } from './routes/tax_.regions.$id'
import { Route as StoreRegionsIdEditRouteImport } from './routes/store_.regions.$id.edit'
import { Route as StoreSalesChannelsIdEditRouteImport } from './routes/store_.sales-channels.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionRoute = SectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketsRoute = BasketsRouteImport.update({
  id: '/baskets',
  path: '/baskets',
  getParentRoute: () => rootRouteImport,
} as any)
const CartsRoute = CartsRouteImport.update({
  id: '/carts',
  path: '/carts',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditRoute = CreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const FulfilmentRoute = FulfilmentRouteImport.update({
  id: '/fulfilment',
  path: '/fulfilment',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketsIdRoute = BasketsIdRouteImport.update({
  id: '/baskets_/$id',
  path: '/baskets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditIdRoute = CreditIdRouteImport.update({
  id: '/credit_/$id',
  path: '/credit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers_/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FulfilmentIndexRoute = FulfilmentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FulfilmentRoute,
} as any)
const FulfilmentProvidersRoute = FulfilmentProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => FulfilmentRoute,
} as any)
const FulfilmentSetsRoute = FulfilmentSetsRouteImport.update({
  id: '/sets',
  path: '/sets',
  getParentRoute: () => FulfilmentRoute,
} as any)
const FulfilmentShippingOptionTypesRoute =
  FulfilmentShippingOptionTypesRouteImport.update({
    id: '/shipping-option-types',
    path: '/shipping-option-types',
    getParentRoute: () => FulfilmentRoute,
  } as any)
const FulfilmentShippingOptionsRoute =
  FulfilmentShippingOptionsRouteImport.update({
    id: '/shipping-options',
    path: '/shipping-options',
    getParentRoute: () => FulfilmentRoute,
  } as any)
const FulfilmentShippingProfilesRoute =
  FulfilmentShippingProfilesRouteImport.update({
    id: '/shipping-profiles',
    path: '/shipping-profiles',
    getParentRoute: () => FulfilmentRoute,
  } as any)
const InventoryIdRoute = InventoryIdRouteImport.update({
  id: '/inventory_/$id',
  path: '/inventory/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders_/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PaymentsRoute,
} as any)
const PaymentsRefundReasonsRoute = PaymentsRefundReasonsRouteImport.update({
  id: '/refund-reasons',
  path: '/refund-reasons',
  getParentRoute: () => PaymentsRoute,
} as any)
const PaymentsIdRoute = PaymentsIdRouteImport.update({
  id: '/payments_/$id',
  path: '/payments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsIndexRoute = PayoutsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PayoutsRoute,
} as any)
const PayoutsCommissionRulesRoute = PayoutsCommissionRulesRouteImport.update({
  id: '/commission-rules',
  path: '/commission-rules',
  getParentRoute: () => PayoutsRoute,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PricingRoute,
} as any)
const PricingPriceListsRoute = PricingPriceListsRouteImport.update({
  id: '/price-lists',
  path: '/price-lists',
  getParentRoute: () => PricingRoute,
} as any)
const PricingPricePreferencesRoute = PricingPricePreferencesRouteImport.update({
  id: '/price-preferences',
  path: '/price-preferences',
  getParentRoute: () => PricingRoute,
} as any)
const PricingPriceSetsRoute = PricingPriceSetsRouteImport.update({
  id: '/price-sets',
  path: '/price-sets',
  getParentRoute: () => PricingRoute,
} as any)
const PricingPricesRoute = PricingPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => PricingRoute,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products_/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsIdRoute = PromotionsIdRouteImport.update({
  id: '/promotions_/$id',
  path: '/promotions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCurrenciesRoute = StoreCurrenciesRouteImport.update({
  id: '/currencies',
  path: '/currencies',
  getParentRoute: () => StoreRoute,
} as any)
const StoreKeysRoute = StoreKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => StoreRoute,
} as any)
const StoreRegionsRoute = StoreRegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => StoreRoute,
} as any)
const StoreSalesChannelsRoute = StoreSalesChannelsRouteImport.update({
  id: '/sales-channels',
  path: '/sales-channels',
  getParentRoute: () => StoreRoute,
} as any)
const SubscriptionsIdRoute = SubscriptionsIdRouteImport.update({
  id: '/subscriptions_/$id',
  path: '/subscriptions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxIndexRoute = TaxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TaxRoute,
} as any)
const TaxRatesRoute = TaxRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => TaxRoute,
} as any)
const TaxRegionsRoute = TaxRegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => TaxRoute,
} as any)
const TaxRegistrationsRoute = TaxRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => TaxRoute,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsDeadLettersRoute = WorkflowsDeadLettersRouteImport.update({
  id: '/dead-letters',
  path: '/dead-letters',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsIdRoute = WorkflowsIdRouteImport.update({
  id: '/workflows_/$id',
  path: '/workflows/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdEditRoute = CustomersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CustomersIdRoute,
} as any)
const FulfilmentShippingOptionsIdRoute =
  FulfilmentShippingOptionsIdRouteImport.update({
    id: '/fulfilment_/shipping-options/$id',
    path: '/fulfilment/shipping-options/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const FulfilmentShippingProfilesIdRoute =
  FulfilmentShippingProfilesIdRouteImport.update({
    id: '/fulfilment_/shipping-profiles/$id',
    path: '/fulfilment/shipping-profiles/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const PricingPriceListsIdRoute = PricingPriceListsIdRouteImport.update({
  id: '/pricing_/price-lists/$id',
  path: '/pricing/price-lists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdEditRoute = ProductsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProductsIdRoute,
} as any)
const PromotionsIdEditRoute = PromotionsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PromotionsIdRoute,
} as any)
const StoreCurrenciesNewRoute = StoreCurrenciesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StoreCurrenciesRoute,
} as any)
const StoreKeysNewRoute = StoreKeysNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StoreKeysRoute,
} as any)
const StoreRegionsNewRoute = StoreRegionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StoreRegionsRoute,
} as any)
const StoreSalesChannelsNewRoute = StoreSalesChannelsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StoreSalesChannelsRoute,
} as any)
const StoreRegionsIdRoute = StoreRegionsIdRouteImport.update({
  id: '/store_/regions/$id',
  path: '/store/regions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSalesChannelsIdRoute = StoreSalesChannelsIdRouteImport.update({
  id: '/store_/sales-channels/$id',
  path: '/store/sales-channels/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxRatesIdRoute = TaxRatesIdRouteImport.update({
  id: '/tax_/rates/$id',
  path: '/tax/rates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxRegionsIdRoute = TaxRegionsIdRouteImport.update({
  id: '/tax_/regions/$id',
  path: '/tax/regions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRegionsIdEditRoute = StoreRegionsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => StoreRegionsIdRoute,
} as any)
const StoreSalesChannelsIdEditRoute =
  StoreSalesChannelsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => StoreSalesChannelsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/baskets': typeof BasketsRoute
  '/carts': typeof CartsRoute
  '/credit': typeof CreditRoute
  '/customers': typeof CustomersRoute
  '/fulfilment': typeof FulfilmentRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRouteWithChildren
  '/payouts': typeof PayoutsRouteWithChildren
  '/pricing': typeof PricingRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/promotions': typeof PromotionsRoute
  '/store': typeof StoreRouteWithChildren
  '/subscriptions': typeof SubscriptionsRoute
  '/tax': typeof TaxRouteWithChildren
  '/workflows': typeof WorkflowsRouteWithChildren
  '/baskets/$id': typeof BasketsIdRoute
  '/credit/$id': typeof CreditIdRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/fulfilment/providers': typeof FulfilmentProvidersRoute
  '/fulfilment/sets': typeof FulfilmentSetsRoute
  '/fulfilment/shipping-option-types': typeof FulfilmentShippingOptionTypesRoute
  '/fulfilment/shipping-options': typeof FulfilmentShippingOptionsRoute
  '/fulfilment/shipping-profiles': typeof FulfilmentShippingProfilesRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/payments/refund-reasons': typeof PaymentsRefundReasonsRoute
  '/payments/$id': typeof PaymentsIdRoute
  '/payouts/commission-rules': typeof PayoutsCommissionRulesRoute
  '/pricing/price-lists': typeof PricingPriceListsRoute
  '/pricing/price-preferences': typeof PricingPricePreferencesRoute
  '/pricing/price-sets': typeof PricingPriceSetsRoute
  '/pricing/prices': typeof PricingPricesRoute
  '/products/new': typeof ProductsNewRoute
  '/products/$id': typeof ProductsIdRouteWithChildren
  '/promotions/$id': typeof PromotionsIdRouteWithChildren
  '/store/currencies': typeof StoreCurrenciesRouteWithChildren
  '/store/keys': typeof StoreKeysRouteWithChildren
  '/store/regions': typeof StoreRegionsRouteWithChildren
  '/store/sales-channels': typeof StoreSalesChannelsRouteWithChildren
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/tax/rates': typeof TaxRatesRoute
  '/tax/regions': typeof TaxRegionsRoute
  '/tax/registrations': typeof TaxRegistrationsRoute
  '/workflows/dead-letters': typeof WorkflowsDeadLettersRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/fulfilment/': typeof FulfilmentIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/payouts/': typeof PayoutsIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/store/': typeof StoreIndexRoute
  '/tax/': typeof TaxIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/fulfilment/shipping-options/$id': typeof FulfilmentShippingOptionsIdRoute
  '/fulfilment/shipping-profiles/$id': typeof FulfilmentShippingProfilesIdRoute
  '/pricing/price-lists/$id': typeof PricingPriceListsIdRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
  '/promotions/$id/edit': typeof PromotionsIdEditRoute
  '/store/currencies/new': typeof StoreCurrenciesNewRoute
  '/store/keys/new': typeof StoreKeysNewRoute
  '/store/regions/new': typeof StoreRegionsNewRoute
  '/store/sales-channels/new': typeof StoreSalesChannelsNewRoute
  '/store/regions/$id': typeof StoreRegionsIdRouteWithChildren
  '/store/sales-channels/$id': typeof StoreSalesChannelsIdRouteWithChildren
  '/tax/rates/$id': typeof TaxRatesIdRoute
  '/tax/regions/$id': typeof TaxRegionsIdRoute
  '/store/regions/$id/edit': typeof StoreRegionsIdEditRoute
  '/store/sales-channels/$id/edit': typeof StoreSalesChannelsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/baskets': typeof BasketsRoute
  '/carts': typeof CartsRoute
  '/credit': typeof CreditRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRouteWithChildren
  '/promotions': typeof PromotionsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/baskets/$id': typeof BasketsIdRoute
  '/credit/$id': typeof CreditIdRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/fulfilment/providers': typeof FulfilmentProvidersRoute
  '/fulfilment/sets': typeof FulfilmentSetsRoute
  '/fulfilment/shipping-option-types': typeof FulfilmentShippingOptionTypesRoute
  '/fulfilment/shipping-options': typeof FulfilmentShippingOptionsRoute
  '/fulfilment/shipping-profiles': typeof FulfilmentShippingProfilesRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/payments/refund-reasons': typeof PaymentsRefundReasonsRoute
  '/payments/$id': typeof PaymentsIdRoute
  '/payouts/commission-rules': typeof PayoutsCommissionRulesRoute
  '/pricing/price-lists': typeof PricingPriceListsRoute
  '/pricing/price-preferences': typeof PricingPricePreferencesRoute
  '/pricing/price-sets': typeof PricingPriceSetsRoute
  '/pricing/prices': typeof PricingPricesRoute
  '/products/new': typeof ProductsNewRoute
  '/products/$id': typeof ProductsIdRouteWithChildren
  '/promotions/$id': typeof PromotionsIdRouteWithChildren
  '/store/currencies': typeof StoreCurrenciesRouteWithChildren
  '/store/keys': typeof StoreKeysRouteWithChildren
  '/store/regions': typeof StoreRegionsRouteWithChildren
  '/store/sales-channels': typeof StoreSalesChannelsRouteWithChildren
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/tax/rates': typeof TaxRatesRoute
  '/tax/regions': typeof TaxRegionsRoute
  '/tax/registrations': typeof TaxRegistrationsRoute
  '/workflows/dead-letters': typeof WorkflowsDeadLettersRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/fulfilment': typeof FulfilmentIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/payouts': typeof PayoutsIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/store': typeof StoreIndexRoute
  '/tax': typeof TaxIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/fulfilment/shipping-options/$id': typeof FulfilmentShippingOptionsIdRoute
  '/fulfilment/shipping-profiles/$id': typeof FulfilmentShippingProfilesIdRoute
  '/pricing/price-lists/$id': typeof PricingPriceListsIdRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
  '/promotions/$id/edit': typeof PromotionsIdEditRoute
  '/store/currencies/new': typeof StoreCurrenciesNewRoute
  '/store/keys/new': typeof StoreKeysNewRoute
  '/store/regions/new': typeof StoreRegionsNewRoute
  '/store/sales-channels/new': typeof StoreSalesChannelsNewRoute
  '/store/regions/$id': typeof StoreRegionsIdRouteWithChildren
  '/store/sales-channels/$id': typeof StoreSalesChannelsIdRouteWithChildren
  '/tax/rates/$id': typeof TaxRatesIdRoute
  '/tax/regions/$id': typeof TaxRegionsIdRoute
  '/store/regions/$id/edit': typeof StoreRegionsIdEditRoute
  '/store/sales-channels/$id/edit': typeof StoreSalesChannelsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/baskets': typeof BasketsRoute
  '/carts': typeof CartsRoute
  '/credit': typeof CreditRoute
  '/customers': typeof CustomersRoute
  '/fulfilment': typeof FulfilmentRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRouteWithChildren
  '/payouts': typeof PayoutsRouteWithChildren
  '/pricing': typeof PricingRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/promotions': typeof PromotionsRoute
  '/store': typeof StoreRouteWithChildren
  '/subscriptions': typeof SubscriptionsRoute
  '/tax': typeof TaxRouteWithChildren
  '/workflows': typeof WorkflowsRouteWithChildren
  '/baskets_/$id': typeof BasketsIdRoute
  '/credit_/$id': typeof CreditIdRoute
  '/customers_/$id': typeof CustomersIdRouteWithChildren
  '/fulfilment/providers': typeof FulfilmentProvidersRoute
  '/fulfilment/sets': typeof FulfilmentSetsRoute
  '/fulfilment/shipping-option-types': typeof FulfilmentShippingOptionTypesRoute
  '/fulfilment/shipping-options': typeof FulfilmentShippingOptionsRoute
  '/fulfilment/shipping-profiles': typeof FulfilmentShippingProfilesRoute
  '/inventory_/$id': typeof InventoryIdRoute
  '/orders_/$id': typeof OrdersIdRoute
  '/payments/refund-reasons': typeof PaymentsRefundReasonsRoute
  '/payments_/$id': typeof PaymentsIdRoute
  '/payouts/commission-rules': typeof PayoutsCommissionRulesRoute
  '/pricing/price-lists': typeof PricingPriceListsRoute
  '/pricing/price-preferences': typeof PricingPricePreferencesRoute
  '/pricing/price-sets': typeof PricingPriceSetsRoute
  '/pricing/prices': typeof PricingPricesRoute
  '/products/new': typeof ProductsNewRoute
  '/products_/$id': typeof ProductsIdRouteWithChildren
  '/promotions_/$id': typeof PromotionsIdRouteWithChildren
  '/store/currencies': typeof StoreCurrenciesRouteWithChildren
  '/store/keys': typeof StoreKeysRouteWithChildren
  '/store/regions': typeof StoreRegionsRouteWithChildren
  '/store/sales-channels': typeof StoreSalesChannelsRouteWithChildren
  '/subscriptions_/$id': typeof SubscriptionsIdRoute
  '/tax/rates': typeof TaxRatesRoute
  '/tax/regions': typeof TaxRegionsRoute
  '/tax/registrations': typeof TaxRegistrationsRoute
  '/workflows/dead-letters': typeof WorkflowsDeadLettersRoute
  '/workflows_/$id': typeof WorkflowsIdRoute
  '/fulfilment/': typeof FulfilmentIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/payouts/': typeof PayoutsIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/store/': typeof StoreIndexRoute
  '/tax/': typeof TaxIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/customers_/$id/edit': typeof CustomersIdEditRoute
  '/fulfilment_/shipping-options/$id': typeof FulfilmentShippingOptionsIdRoute
  '/fulfilment_/shipping-profiles/$id': typeof FulfilmentShippingProfilesIdRoute
  '/pricing_/price-lists/$id': typeof PricingPriceListsIdRoute
  '/products_/$id/edit': typeof ProductsIdEditRoute
  '/promotions_/$id/edit': typeof PromotionsIdEditRoute
  '/store/currencies/new': typeof StoreCurrenciesNewRoute
  '/store/keys/new': typeof StoreKeysNewRoute
  '/store/regions/new': typeof StoreRegionsNewRoute
  '/store/sales-channels/new': typeof StoreSalesChannelsNewRoute
  '/store_/regions/$id': typeof StoreRegionsIdRouteWithChildren
  '/store_/sales-channels/$id': typeof StoreSalesChannelsIdRouteWithChildren
  '/tax_/rates/$id': typeof TaxRatesIdRoute
  '/tax_/regions/$id': typeof TaxRegionsIdRoute
  '/store_/regions/$id/edit': typeof StoreRegionsIdEditRoute
  '/store_/sales-channels/$id/edit': typeof StoreSalesChannelsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$section'
    | '/baskets'
    | '/carts'
    | '/credit'
    | '/customers'
    | '/fulfilment'
    | '/inventory'
    | '/orders'
    | '/payments'
    | '/payouts'
    | '/pricing'
    | '/products'
    | '/promotions'
    | '/store'
    | '/subscriptions'
    | '/tax'
    | '/workflows'
    | '/baskets/$id'
    | '/credit/$id'
    | '/customers/$id'
    | '/fulfilment/providers'
    | '/fulfilment/sets'
    | '/fulfilment/shipping-option-types'
    | '/fulfilment/shipping-options'
    | '/fulfilment/shipping-profiles'
    | '/inventory/$id'
    | '/orders/$id'
    | '/payments/refund-reasons'
    | '/payments/$id'
    | '/payouts/commission-rules'
    | '/pricing/price-lists'
    | '/pricing/price-preferences'
    | '/pricing/price-sets'
    | '/pricing/prices'
    | '/products/new'
    | '/products/$id'
    | '/promotions/$id'
    | '/store/currencies'
    | '/store/keys'
    | '/store/regions'
    | '/store/sales-channels'
    | '/subscriptions/$id'
    | '/tax/rates'
    | '/tax/regions'
    | '/tax/registrations'
    | '/workflows/dead-letters'
    | '/workflows/$id'
    | '/fulfilment/'
    | '/payments/'
    | '/payouts/'
    | '/pricing/'
    | '/store/'
    | '/tax/'
    | '/workflows/'
    | '/customers/$id/edit'
    | '/fulfilment/shipping-options/$id'
    | '/fulfilment/shipping-profiles/$id'
    | '/pricing/price-lists/$id'
    | '/products/$id/edit'
    | '/promotions/$id/edit'
    | '/store/currencies/new'
    | '/store/keys/new'
    | '/store/regions/new'
    | '/store/sales-channels/new'
    | '/store/regions/$id'
    | '/store/sales-channels/$id'
    | '/tax/rates/$id'
    | '/tax/regions/$id'
    | '/store/regions/$id/edit'
    | '/store/sales-channels/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$section'
    | '/baskets'
    | '/carts'
    | '/credit'
    | '/customers'
    | '/inventory'
    | '/orders'
    | '/products'
    | '/promotions'
    | '/subscriptions'
    | '/baskets/$id'
    | '/credit/$id'
    | '/customers/$id'
    | '/fulfilment/providers'
    | '/fulfilment/sets'
    | '/fulfilment/shipping-option-types'
    | '/fulfilment/shipping-options'
    | '/fulfilment/shipping-profiles'
    | '/inventory/$id'
    | '/orders/$id'
    | '/payments/refund-reasons'
    | '/payments/$id'
    | '/payouts/commission-rules'
    | '/pricing/price-lists'
    | '/pricing/price-preferences'
    | '/pricing/price-sets'
    | '/pricing/prices'
    | '/products/new'
    | '/products/$id'
    | '/promotions/$id'
    | '/store/currencies'
    | '/store/keys'
    | '/store/regions'
    | '/store/sales-channels'
    | '/subscriptions/$id'
    | '/tax/rates'
    | '/tax/regions'
    | '/tax/registrations'
    | '/workflows/dead-letters'
    | '/workflows/$id'
    | '/fulfilment'
    | '/payments'
    | '/payouts'
    | '/pricing'
    | '/store'
    | '/tax'
    | '/workflows'
    | '/customers/$id/edit'
    | '/fulfilment/shipping-options/$id'
    | '/fulfilment/shipping-profiles/$id'
    | '/pricing/price-lists/$id'
    | '/products/$id/edit'
    | '/promotions/$id/edit'
    | '/store/currencies/new'
    | '/store/keys/new'
    | '/store/regions/new'
    | '/store/sales-channels/new'
    | '/store/regions/$id'
    | '/store/sales-channels/$id'
    | '/tax/rates/$id'
    | '/tax/regions/$id'
    | '/store/regions/$id/edit'
    | '/store/sales-channels/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/$section'
    | '/baskets'
    | '/carts'
    | '/credit'
    | '/customers'
    | '/fulfilment'
    | '/inventory'
    | '/orders'
    | '/payments'
    | '/payouts'
    | '/pricing'
    | '/products'
    | '/promotions'
    | '/store'
    | '/subscriptions'
    | '/tax'
    | '/workflows'
    | '/baskets_/$id'
    | '/credit_/$id'
    | '/customers_/$id'
    | '/fulfilment/providers'
    | '/fulfilment/sets'
    | '/fulfilment/shipping-option-types'
    | '/fulfilment/shipping-options'
    | '/fulfilment/shipping-profiles'
    | '/inventory_/$id'
    | '/orders_/$id'
    | '/payments/refund-reasons'
    | '/payments_/$id'
    | '/payouts/commission-rules'
    | '/pricing/price-lists'
    | '/pricing/price-preferences'
    | '/pricing/price-sets'
    | '/pricing/prices'
    | '/products/new'
    | '/products_/$id'
    | '/promotions_/$id'
    | '/store/currencies'
    | '/store/keys'
    | '/store/regions'
    | '/store/sales-channels'
    | '/subscriptions_/$id'
    | '/tax/rates'
    | '/tax/regions'
    | '/tax/registrations'
    | '/workflows/dead-letters'
    | '/workflows_/$id'
    | '/fulfilment/'
    | '/payments/'
    | '/payouts/'
    | '/pricing/'
    | '/store/'
    | '/tax/'
    | '/workflows/'
    | '/customers_/$id/edit'
    | '/fulfilment_/shipping-options/$id'
    | '/fulfilment_/shipping-profiles/$id'
    | '/pricing_/price-lists/$id'
    | '/products_/$id/edit'
    | '/promotions_/$id/edit'
    | '/store/currencies/new'
    | '/store/keys/new'
    | '/store/regions/new'
    | '/store/sales-channels/new'
    | '/store_/regions/$id'
    | '/store_/sales-channels/$id'
    | '/tax_/rates/$id'
    | '/tax_/regions/$id'
    | '/store_/regions/$id/edit'
    | '/store_/sales-channels/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectionRoute: typeof SectionRoute
  BasketsRoute: typeof BasketsRoute
  CartsRoute: typeof CartsRoute
  CreditRoute: typeof CreditRoute
  CustomersRoute: typeof CustomersRoute
  FulfilmentRoute: typeof FulfilmentRouteWithChildren
  InventoryRoute: typeof InventoryRoute
  OrdersRoute: typeof OrdersRoute
  PaymentsRoute: typeof PaymentsRouteWithChildren
  PayoutsRoute: typeof PayoutsRouteWithChildren
  PricingRoute: typeof PricingRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  PromotionsRoute: typeof PromotionsRoute
  StoreRoute: typeof StoreRouteWithChildren
  SubscriptionsRoute: typeof SubscriptionsRoute
  TaxRoute: typeof TaxRouteWithChildren
  WorkflowsRoute: typeof WorkflowsRouteWithChildren
  BasketsIdRoute: typeof BasketsIdRoute
  CreditIdRoute: typeof CreditIdRoute
  CustomersIdRoute: typeof CustomersIdRouteWithChildren
  InventoryIdRoute: typeof InventoryIdRoute
  OrdersIdRoute: typeof OrdersIdRoute
  PaymentsIdRoute: typeof PaymentsIdRoute
  ProductsIdRoute: typeof ProductsIdRouteWithChildren
  PromotionsIdRoute: typeof PromotionsIdRouteWithChildren
  SubscriptionsIdRoute: typeof SubscriptionsIdRoute
  WorkflowsIdRoute: typeof WorkflowsIdRoute
  FulfilmentShippingOptionsIdRoute: typeof FulfilmentShippingOptionsIdRoute
  FulfilmentShippingProfilesIdRoute: typeof FulfilmentShippingProfilesIdRoute
  PricingPriceListsIdRoute: typeof PricingPriceListsIdRoute
  StoreRegionsIdRoute: typeof StoreRegionsIdRouteWithChildren
  StoreSalesChannelsIdRoute: typeof StoreSalesChannelsIdRouteWithChildren
  TaxRatesIdRoute: typeof TaxRatesIdRoute
  TaxRegionsIdRoute: typeof TaxRegionsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section': {
      id: '/$section'
      path: '/$section'
      fullPath: '/$section'
      preLoaderRoute: typeof SectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baskets': {
      id: '/baskets'
      path: '/baskets'
      fullPath: '/baskets'
      preLoaderRoute: typeof BasketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carts': {
      id: '/carts'
      path: '/carts'
      fullPath: '/carts'
      preLoaderRoute: typeof CartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit': {
      id: '/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof CreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fulfilment': {
      id: '/fulfilment'
      path: '/fulfilment'
      fullPath: '/fulfilment'
      preLoaderRoute: typeof FulfilmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baskets_/$id': {
      id: '/baskets_/$id'
      path: '/baskets/$id'
      fullPath: '/baskets/$id'
      preLoaderRoute: typeof BasketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit_/$id': {
      id: '/credit_/$id'
      path: '/credit/$id'
      fullPath: '/credit/$id'
      preLoaderRoute: typeof CreditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers_/$id': {
      id: '/customers_/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fulfilment/': {
      id: '/fulfilment/'
      path: '/'
      fullPath: '/fulfilment/'
      preLoaderRoute: typeof FulfilmentIndexRouteImport
      parentRoute: typeof FulfilmentRoute
    }
    '/fulfilment/providers': {
      id: '/fulfilment/providers'
      path: '/providers'
      fullPath: '/fulfilment/providers'
      preLoaderRoute: typeof FulfilmentProvidersRouteImport
      parentRoute: typeof FulfilmentRoute
    }
    '/fulfilment/sets': {
      id: '/fulfilment/sets'
      path: '/sets'
      fullPath: '/fulfilment/sets'
      preLoaderRoute: typeof FulfilmentSetsRouteImport
      parentRoute: typeof FulfilmentRoute
    }
    '/fulfilment/shipping-option-types': {
      id: '/fulfilment/shipping-option-types'
      path: '/shipping-option-types'
      fullPath: '/fulfilment/shipping-option-types'
      preLoaderRoute: typeof FulfilmentShippingOptionTypesRouteImport
      parentRoute: typeof FulfilmentRoute
    }
    '/fulfilment/shipping-options': {
      id: '/fulfilment/shipping-options'
      path: '/shipping-options'
      fullPath: '/fulfilment/shipping-options'
      preLoaderRoute: typeof FulfilmentShippingOptionsRouteImport
      parentRoute: typeof FulfilmentRoute
    }
    '/fulfilment/shipping-profiles': {
      id: '/fulfilment/shipping-profiles'
      path: '/shipping-profiles'
      fullPath: '/fulfilment/shipping-profiles'
      preLoaderRoute: typeof FulfilmentShippingProfilesRouteImport
      parentRoute: typeof FulfilmentRoute
    }
    '/inventory_/$id': {
      id: '/inventory_/$id'
      path: '/inventory/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof InventoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders_/$id': {
      id: '/orders_/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof PaymentsRoute
    }
    '/payments/refund-reasons': {
      id: '/payments/refund-reasons'
      path: '/refund-reasons'
      fullPath: '/payments/refund-reasons'
      preLoaderRoute: typeof PaymentsRefundReasonsRouteImport
      parentRoute: typeof PaymentsRoute
    }
    '/payments_/$id': {
      id: '/payments_/$id'
      path: '/payments/$id'
      fullPath: '/payments/$id'
      preLoaderRoute: typeof PaymentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts/': {
      id: '/payouts/'
      path: '/'
      fullPath: '/payouts/'
      preLoaderRoute: typeof PayoutsIndexRouteImport
      parentRoute: typeof PayoutsRoute
    }
    '/payouts/commission-rules': {
      id: '/payouts/commission-rules'
      path: '/commission-rules'
      fullPath: '/payouts/commission-rules'
      preLoaderRoute: typeof PayoutsCommissionRulesRouteImport
      parentRoute: typeof PayoutsRoute
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/'
      fullPath: '/pricing/'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof PricingRoute
    }
    '/pricing/price-lists': {
      id: '/pricing/price-lists'
      path: '/price-lists'
      fullPath: '/pricing/price-lists'
      preLoaderRoute: typeof PricingPriceListsRouteImport
      parentRoute: typeof PricingRoute
    }
    '/pricing/price-preferences': {
      id: '/pricing/price-preferences'
      path: '/price-preferences'
      fullPath: '/pricing/price-preferences'
      preLoaderRoute: typeof PricingPricePreferencesRouteImport
      parentRoute: typeof PricingRoute
    }
    '/pricing/price-sets': {
      id: '/pricing/price-sets'
      path: '/price-sets'
      fullPath: '/pricing/price-sets'
      preLoaderRoute: typeof PricingPriceSetsRouteImport
      parentRoute: typeof PricingRoute
    }
    '/pricing/prices': {
      id: '/pricing/prices'
      path: '/prices'
      fullPath: '/pricing/prices'
      preLoaderRoute: typeof PricingPricesRouteImport
      parentRoute: typeof PricingRoute
    }
    '/products/new': {
      id: '/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products_/$id': {
      id: '/products_/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions_/$id': {
      id: '/promotions_/$id'
      path: '/promotions/$id'
      fullPath: '/promotions/$id'
      preLoaderRoute: typeof PromotionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/currencies': {
      id: '/store/currencies'
      path: '/currencies'
      fullPath: '/store/currencies'
      preLoaderRoute: typeof StoreCurrenciesRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/keys': {
      id: '/store/keys'
      path: '/keys'
      fullPath: '/store/keys'
      preLoaderRoute: typeof StoreKeysRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/regions': {
      id: '/store/regions'
      path: '/regions'
      fullPath: '/store/regions'
      preLoaderRoute: typeof StoreRegionsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/sales-channels': {
      id: '/store/sales-channels'
      path: '/sales-channels'
      fullPath: '/store/sales-channels'
      preLoaderRoute: typeof StoreSalesChannelsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/subscriptions_/$id': {
      id: '/subscriptions_/$id'
      path: '/subscriptions/$id'
      fullPath: '/subscriptions/$id'
      preLoaderRoute: typeof SubscriptionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax/': {
      id: '/tax/'
      path: '/'
      fullPath: '/tax/'
      preLoaderRoute: typeof TaxIndexRouteImport
      parentRoute: typeof TaxRoute
    }
    '/tax/rates': {
      id: '/tax/rates'
      path: '/rates'
      fullPath: '/tax/rates'
      preLoaderRoute: typeof TaxRatesRouteImport
      parentRoute: typeof TaxRoute
    }
    '/tax/regions': {
      id: '/tax/regions'
      path: '/regions'
      fullPath: '/tax/regions'
      preLoaderRoute: typeof TaxRegionsRouteImport
      parentRoute: typeof TaxRoute
    }
    '/tax/registrations': {
      id: '/tax/registrations'
      path: '/registrations'
      fullPath: '/tax/registrations'
      preLoaderRoute: typeof TaxRegistrationsRouteImport
      parentRoute: typeof TaxRoute
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/dead-letters': {
      id: '/workflows/dead-letters'
      path: '/dead-letters'
      fullPath: '/workflows/dead-letters'
      preLoaderRoute: typeof WorkflowsDeadLettersRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows_/$id': {
      id: '/workflows_/$id'
      path: '/workflows/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof WorkflowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers_/$id/edit': {
      id: '/customers_/$id/edit'
      path: '/edit'
      fullPath: '/customers/$id/edit'
      preLoaderRoute: typeof CustomersIdEditRouteImport
      parentRoute: typeof CustomersIdRoute
    }
    '/fulfilment_/shipping-options/$id': {
      id: '/fulfilment_/shipping-options/$id'
      path: '/fulfilment/shipping-options/$id'
      fullPath: '/fulfilment/shipping-options/$id'
      preLoaderRoute: typeof FulfilmentShippingOptionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fulfilment_/shipping-profiles/$id': {
      id: '/fulfilment_/shipping-profiles/$id'
      path: '/fulfilment/shipping-profiles/$id'
      fullPath: '/fulfilment/shipping-profiles/$id'
      preLoaderRoute: typeof FulfilmentShippingProfilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing_/price-lists/$id': {
      id: '/pricing_/price-lists/$id'
      path: '/pricing/price-lists/$id'
      fullPath: '/pricing/price-lists/$id'
      preLoaderRoute: typeof PricingPriceListsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$id/edit': {
      id: '/products_/$id/edit'
      path: '/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof ProductsIdEditRouteImport
      parentRoute: typeof ProductsIdRoute
    }
    '/promotions_/$id/edit': {
      id: '/promotions_/$id/edit'
      path: '/edit'
      fullPath: '/promotions/$id/edit'
      preLoaderRoute: typeof PromotionsIdEditRouteImport
      parentRoute: typeof PromotionsIdRoute
    }
    '/store/currencies/new': {
      id: '/store/currencies/new'
      path: '/new'
      fullPath: '/store/currencies/new'
      preLoaderRoute: typeof StoreCurrenciesNewRouteImport
      parentRoute: typeof StoreCurrenciesRoute
    }
    '/store/keys/new': {
      id: '/store/keys/new'
      path: '/new'
      fullPath: '/store/keys/new'
      preLoaderRoute: typeof StoreKeysNewRouteImport
      parentRoute: typeof StoreKeysRoute
    }
    '/store/regions/new': {
      id: '/store/regions/new'
      path: '/new'
      fullPath: '/store/regions/new'
      preLoaderRoute: typeof StoreRegionsNewRouteImport
      parentRoute: typeof StoreRegionsRoute
    }
    '/store/sales-channels/new': {
      id: '/store/sales-channels/new'
      path: '/new'
      fullPath: '/store/sales-channels/new'
      preLoaderRoute: typeof StoreSalesChannelsNewRouteImport
      parentRoute: typeof StoreSalesChannelsRoute
    }
    '/store_/regions/$id': {
      id: '/store_/regions/$id'
      path: '/store/regions/$id'
      fullPath: '/store/regions/$id'
      preLoaderRoute: typeof StoreRegionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store_/sales-channels/$id': {
      id: '/store_/sales-channels/$id'
      path: '/store/sales-channels/$id'
      fullPath: '/store/sales-channels/$id'
      preLoaderRoute: typeof StoreSalesChannelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax_/rates/$id': {
      id: '/tax_/rates/$id'
      path: '/tax/rates/$id'
      fullPath: '/tax/rates/$id'
      preLoaderRoute: typeof TaxRatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax_/regions/$id': {
      id: '/tax_/regions/$id'
      path: '/tax/regions/$id'
      fullPath: '/tax/regions/$id'
      preLoaderRoute: typeof TaxRegionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store_/regions/$id/edit': {
      id: '/store_/regions/$id/edit'
      path: '/edit'
      fullPath: '/store/regions/$id/edit'
      preLoaderRoute: typeof StoreRegionsIdEditRouteImport
      parentRoute: typeof StoreRegionsIdRoute
    }
    '/store_/sales-channels/$id/edit': {
      id: '/store_/sales-channels/$id/edit'
      path: '/edit'
      fullPath: '/store/sales-channels/$id/edit'
      preLoaderRoute: typeof StoreSalesChannelsIdEditRouteImport
      parentRoute: typeof StoreSalesChannelsIdRoute
    }
  }
}

interface FulfilmentRouteChildren {
  FulfilmentProvidersRoute: typeof FulfilmentProvidersRoute
  FulfilmentSetsRoute: typeof FulfilmentSetsRoute
  FulfilmentShippingOptionTypesRoute: typeof FulfilmentShippingOptionTypesRoute
  FulfilmentShippingOptionsRoute: typeof FulfilmentShippingOptionsRoute
  FulfilmentShippingProfilesRoute: typeof FulfilmentShippingProfilesRoute
  FulfilmentIndexRoute: typeof FulfilmentIndexRoute
}

const FulfilmentRouteChildren: FulfilmentRouteChildren = {
  FulfilmentProvidersRoute: FulfilmentProvidersRoute,
  FulfilmentSetsRoute: FulfilmentSetsRoute,
  FulfilmentShippingOptionTypesRoute: FulfilmentShippingOptionTypesRoute,
  FulfilmentShippingOptionsRoute: FulfilmentShippingOptionsRoute,
  FulfilmentShippingProfilesRoute: FulfilmentShippingProfilesRoute,
  FulfilmentIndexRoute: FulfilmentIndexRoute,
}

const FulfilmentRouteWithChildren = FulfilmentRoute._addFileChildren(
  FulfilmentRouteChildren,
)

interface PaymentsRouteChildren {
  PaymentsRefundReasonsRoute: typeof PaymentsRefundReasonsRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
}

const PaymentsRouteChildren: PaymentsRouteChildren = {
  PaymentsRefundReasonsRoute: PaymentsRefundReasonsRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
}

const PaymentsRouteWithChildren = PaymentsRoute._addFileChildren(
  PaymentsRouteChildren,
)

interface PayoutsRouteChildren {
  PayoutsCommissionRulesRoute: typeof PayoutsCommissionRulesRoute
  PayoutsIndexRoute: typeof PayoutsIndexRoute
}

const PayoutsRouteChildren: PayoutsRouteChildren = {
  PayoutsCommissionRulesRoute: PayoutsCommissionRulesRoute,
  PayoutsIndexRoute: PayoutsIndexRoute,
}

const PayoutsRouteWithChildren =
  PayoutsRoute._addFileChildren(PayoutsRouteChildren)

interface PricingRouteChildren {
  PricingPriceListsRoute: typeof PricingPriceListsRoute
  PricingPricePreferencesRoute: typeof PricingPricePreferencesRoute
  PricingPriceSetsRoute: typeof PricingPriceSetsRoute
  PricingPricesRoute: typeof PricingPricesRoute
  PricingIndexRoute: typeof PricingIndexRoute
}

const PricingRouteChildren: PricingRouteChildren = {
  PricingPriceListsRoute: PricingPriceListsRoute,
  PricingPricePreferencesRoute: PricingPricePreferencesRoute,
  PricingPriceSetsRoute: PricingPriceSetsRoute,
  PricingPricesRoute: PricingPricesRoute,
  PricingIndexRoute: PricingIndexRoute,
}

const PricingRouteWithChildren =
  PricingRoute._addFileChildren(PricingRouteChildren)

interface ProductsRouteChildren {
  ProductsNewRoute: typeof ProductsNewRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsNewRoute: ProductsNewRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface StoreCurrenciesRouteChildren {
  StoreCurrenciesNewRoute: typeof StoreCurrenciesNewRoute
}

const StoreCurrenciesRouteChildren: StoreCurrenciesRouteChildren = {
  StoreCurrenciesNewRoute: StoreCurrenciesNewRoute,
}

const StoreCurrenciesRouteWithChildren = StoreCurrenciesRoute._addFileChildren(
  StoreCurrenciesRouteChildren,
)

interface StoreKeysRouteChildren {
  StoreKeysNewRoute: typeof StoreKeysNewRoute
}

const StoreKeysRouteChildren: StoreKeysRouteChildren = {
  StoreKeysNewRoute: StoreKeysNewRoute,
}

const StoreKeysRouteWithChildren = StoreKeysRoute._addFileChildren(
  StoreKeysRouteChildren,
)

interface StoreRegionsRouteChildren {
  StoreRegionsNewRoute: typeof StoreRegionsNewRoute
}

const StoreRegionsRouteChildren: StoreRegionsRouteChildren = {
  StoreRegionsNewRoute: StoreRegionsNewRoute,
}

const StoreRegionsRouteWithChildren = StoreRegionsRoute._addFileChildren(
  StoreRegionsRouteChildren,
)

interface StoreSalesChannelsRouteChildren {
  StoreSalesChannelsNewRoute: typeof StoreSalesChannelsNewRoute
}

const StoreSalesChannelsRouteChildren: StoreSalesChannelsRouteChildren = {
  StoreSalesChannelsNewRoute: StoreSalesChannelsNewRoute,
}

const StoreSalesChannelsRouteWithChildren =
  StoreSalesChannelsRoute._addFileChildren(StoreSalesChannelsRouteChildren)

interface StoreRouteChildren {
  StoreCurrenciesRoute: typeof StoreCurrenciesRouteWithChildren
  StoreKeysRoute: typeof StoreKeysRouteWithChildren
  StoreRegionsRoute: typeof StoreRegionsRouteWithChildren
  StoreSalesChannelsRoute: typeof StoreSalesChannelsRouteWithChildren
  StoreIndexRoute: typeof StoreIndexRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreCurrenciesRoute: StoreCurrenciesRouteWithChildren,
  StoreKeysRoute: StoreKeysRouteWithChildren,
  StoreRegionsRoute: StoreRegionsRouteWithChildren,
  StoreSalesChannelsRoute: StoreSalesChannelsRouteWithChildren,
  StoreIndexRoute: StoreIndexRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface TaxRouteChildren {
  TaxRatesRoute: typeof TaxRatesRoute
  TaxRegionsRoute: typeof TaxRegionsRoute
  TaxRegistrationsRoute: typeof TaxRegistrationsRoute
  TaxIndexRoute: typeof TaxIndexRoute
}

const TaxRouteChildren: TaxRouteChildren = {
  TaxRatesRoute: TaxRatesRoute,
  TaxRegionsRoute: TaxRegionsRoute,
  TaxRegistrationsRoute: TaxRegistrationsRoute,
  TaxIndexRoute: TaxIndexRoute,
}

const TaxRouteWithChildren = TaxRoute._addFileChildren(TaxRouteChildren)

interface WorkflowsRouteChildren {
  WorkflowsDeadLettersRoute: typeof WorkflowsDeadLettersRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

const WorkflowsRouteChildren: WorkflowsRouteChildren = {
  WorkflowsDeadLettersRoute: WorkflowsDeadLettersRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}

const WorkflowsRouteWithChildren = WorkflowsRoute._addFileChildren(
  WorkflowsRouteChildren,
)

interface CustomersIdRouteChildren {
  CustomersIdEditRoute: typeof CustomersIdEditRoute
}

const CustomersIdRouteChildren: CustomersIdRouteChildren = {
  CustomersIdEditRoute: CustomersIdEditRoute,
}

const CustomersIdRouteWithChildren = CustomersIdRoute._addFileChildren(
  CustomersIdRouteChildren,
)

interface ProductsIdRouteChildren {
  ProductsIdEditRoute: typeof ProductsIdEditRoute
}

const ProductsIdRouteChildren: ProductsIdRouteChildren = {
  ProductsIdEditRoute: ProductsIdEditRoute,
}

const ProductsIdRouteWithChildren = ProductsIdRoute._addFileChildren(
  ProductsIdRouteChildren,
)

interface PromotionsIdRouteChildren {
  PromotionsIdEditRoute: typeof PromotionsIdEditRoute
}

const PromotionsIdRouteChildren: PromotionsIdRouteChildren = {
  PromotionsIdEditRoute: PromotionsIdEditRoute,
}

const PromotionsIdRouteWithChildren = PromotionsIdRoute._addFileChildren(
  PromotionsIdRouteChildren,
)

interface StoreRegionsIdRouteChildren {
  StoreRegionsIdEditRoute: typeof StoreRegionsIdEditRoute
}

const StoreRegionsIdRouteChildren: StoreRegionsIdRouteChildren = {
  StoreRegionsIdEditRoute: StoreRegionsIdEditRoute,
}

const StoreRegionsIdRouteWithChildren = StoreRegionsIdRoute._addFileChildren(
  StoreRegionsIdRouteChildren,
)

interface StoreSalesChannelsIdRouteChildren {
  StoreSalesChannelsIdEditRoute: typeof StoreSalesChannelsIdEditRoute
}

const StoreSalesChannelsIdRouteChildren: StoreSalesChannelsIdRouteChildren = {
  StoreSalesChannelsIdEditRoute: StoreSalesChannelsIdEditRoute,
}

const StoreSalesChannelsIdRouteWithChildren =
  StoreSalesChannelsIdRoute._addFileChildren(StoreSalesChannelsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectionRoute: SectionRoute,
  BasketsRoute: BasketsRoute,
  CartsRoute: CartsRoute,
  CreditRoute: CreditRoute,
  CustomersRoute: CustomersRoute,
  FulfilmentRoute: FulfilmentRouteWithChildren,
  InventoryRoute: InventoryRoute,
  OrdersRoute: OrdersRoute,
  PaymentsRoute: PaymentsRouteWithChildren,
  PayoutsRoute: PayoutsRouteWithChildren,
  PricingRoute: PricingRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  PromotionsRoute: PromotionsRoute,
  StoreRoute: StoreRouteWithChildren,
  SubscriptionsRoute: SubscriptionsRoute,
  TaxRoute: TaxRouteWithChildren,
  WorkflowsRoute: WorkflowsRouteWithChildren,
  BasketsIdRoute: BasketsIdRoute,
  CreditIdRoute: CreditIdRoute,
  CustomersIdRoute: CustomersIdRouteWithChildren,
  InventoryIdRoute: InventoryIdRoute,
  OrdersIdRoute: OrdersIdRoute,
  PaymentsIdRoute: PaymentsIdRoute,
  ProductsIdRoute: ProductsIdRouteWithChildren,
  PromotionsIdRoute: PromotionsIdRouteWithChildren,
  SubscriptionsIdRoute: SubscriptionsIdRoute,
  WorkflowsIdRoute: WorkflowsIdRoute,
  FulfilmentShippingOptionsIdRoute: FulfilmentShippingOptionsIdRoute,
  FulfilmentShippingProfilesIdRoute: FulfilmentShippingProfilesIdRoute,
  PricingPriceListsIdRoute: PricingPriceListsIdRoute,
  StoreRegionsIdRoute: StoreRegionsIdRouteWithChildren,
  StoreSalesChannelsIdRoute: StoreSalesChannelsIdRouteWithChildren,
  TaxRatesIdRoute: TaxRatesIdRoute,
  TaxRegionsIdRoute: TaxRegionsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
